Repository labens-ufrn/suggestclasses, pull requests merged in 2020-05, with the labels that each got.

#59 Atualização do branch docentes_sugestao_turma
  core/models.py
  dados/povoar_discentes.py
Labels: Prioridade: Alta, Status: Em Progresso, Tipo: Manuntenção, e/1 🕑

#62 Correções no scritpt de povoamento de horários.
  dados/povoar_horarios.py
Labels: Prioridade: Alta, Status: Aprovado, Tipo: Manuntenção, e/1 🕑

#63 Add migration de alteração de site de departamento
  core/migrations/0070_auto_20200513_1723.py
  templates/registration/login.html
Labels: Prioridade: Baixa, Status: Aprovado, Tipo: Manuntenção, e/1 🕑

#64 Update README.md
  README.md
Labels: Prioridade: Baixa, Status: Aprovado, Tipo: Documentação, e/1 🕑

#66 Atualizando branch docentes_sugestao_turma
  .gitignore
  README.md
  contrib/path.env-sample
  path.env
Labels: Prioridade: Baixa, Status: Aprovado, Tipo: Manuntenção, e/1 🕑

#67 Várias pequenas atualizações
  core/migrations/0071_docente_departamento.py
  core/models.py
  core/static/css/bootstrap.min.css
  core/static/css/bootstrap.min.css.map
  core/static/js/bootstrap.bundle.min.js
  core/static/js/bootstrap.bundle.min.js.map
  core/static/js/bootstrap.min.js
  core/static/js/bootstrap.min.js.map
  core/templates/core/base.html
  core/templates/core/home.html
  core/templates/core/sugestao/grade_horarios.html
  core/templates/core/turmas/grade_horarios.html
  dados/povoar.py
  dados/povoar_docentes.py
  dados/povoar_horarios.py
Labels: Prioridade: Alta, Status: Aprovado, Tipo: Manuntenção, e/1 🕑

#68 Tentando concertar o GitHub Action que deixou de funcionar.
  .github/workflows/pythonapp.yml
Labels: Prioridade: Baixa, Status: Aprovado, Tipo: Manuntenção, e/1 🕑

#74 Alguns ajustes e adicionando novos testes
  core/bo/sugestao.py
  core/bo/turma.py
  core/templates/core/usuario/profile_discente.html
  core/tests/povoar_testes.py
  core/tests/test_sugestao.py
  core/tests/test_turma.py
  core/visoes/suggest_view.py
  dados/povoar_horarios.py
Labels: Prioridade: Baixa, Status: Aprovado, Tipo: Testando, e/1 🕑

#76 Adicionar Fluxograma, Turmas e Sugestões de Turmas de Administração
  .editorconfig
  core/bo/sevices.py
  core/templates/core/flow/list.html
  core/templates/core/sugestao/grade_horarios.html
  core/templates/core/sugestao/list.html
  core/templates/core/turmas/grade_horarios.html
  core/templates/core/turmas/list.html
  core/urls.py
  core/views.py
  core/visoes/flow_view.py
Labels: Prioridade: Alta, Status: Aprovado, Tipo: Funcionalidade

#79 Adição do Fluxograma, Turmas e Sugestões do Curso de Turismo
  core/bo/sevices.py
  core/templates/core/flow/list.html
  core/templates/core/sugestao/list.html
  core/templates/core/turmas/list.html
  core/urls.py
  core/views.py
Labels: Prioridade: Alta, Status: Aprovado, Tipo: Funcionalidade

#60 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Prioridade: Baixa, Status: Aprovado, Tipo: Documentação, e/1 🕑

#61 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Prioridade: Médio, Status: Bloqueado, Status: Em Progresso, Tipo: Documentação, e/4 🕑

#87 Adição de Vínculos Docentes em Turmas
  core/migrations/0072_vinculodocente.py
  core/migrations/0073_auto_20200520_1743.py
  core/models.py
  core/templates/core/turmas/detalhar.html
  core/templates/core/turmas/detalhar_vinculos_docente.html
  core/templates/core/turmas/grade_horarios.html
  core/templates/core/turmas/vinculos_docente_exibir.html
  dados/povoar_turma.py
Labels: Prioridade: Alta, Status: Aprovado, Tipo: Funcionalidade, e/1 🕑

#89 Adição dos Cursos de Letras de Currais Novos
  core/bo/sevices.py
  core/templates/core/flow/list.html
  core/templates/core/sugestao/list.html
  core/templates/core/turmas/list.html
  core/urls.py
  core/views.py
  core/visoes/sugestao_letras_view.py
Labels: Prioridade: Alta, Status: Aprovado, Tipo: Funcionalidade, e/5 🕑

#90 Implementação de funções para adicionar vínculos docentes - parte 1
  README.md
  core/forms.py
  core/templates/core/sugestao/docentes_list_option.html
  core/templates/core/sugestao/editar.html
  core/templates/core/sugestao/incluir.html
  core/templates/core/sugestao/vinculo_docente_list.html
  core/urls.py
  core/visoes/suggest_view.py
Labels: Prioridade: Alta, Status: Em Progresso, Tipo: Funcionalidade, e/8 🕑
